# Generated by Django 4.2.5 on 2024-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mfg_date',
            field=models.DateField(null=True),
        ),
    ]
